do not use *.spec.in template
use *.spec file with RPM macros instead

- 3.0.1

diff --git a/Makefile.am.common b/Makefile.am.common
--- a/Makefile.am.common
+++ b/Makefile.am.common
@@ -15,6 +15,7 @@ ${ybcfiles}: %.ybc: %.ycp $(ycpchook)
 CLEANFILES = ${ybcfiles}
 DISTCLEANFILES = .dep
 
+if HAS_YCP_MODULES
 # Needs to be outside "." because of cases
 # where ycpchook contains a symlink to "."
 # Otherwise "." keeps being newer than .dep and we loop.
@@ -26,14 +27,16 @@ NEWDEP=${top_builddir}/.dep.new
 	${YCPMAKEDEP} --prefix=${prefix} ${YCPCFLAGS} > ${NEWDEP}
 	cat ${NEWDEP} > .dep
 	rm ${NEWDEP}
+-include .dep
+endif
 
 dist-hook: check-syntax
 
 CHECK_SYNTAX = true
-check-syntax: $(client_DATA) $(ycpchook)
-	@if test "$(client_DATA)"; then \
+check-syntax: $(client_DATA) $(module_DATA) $(ynclude_DATA) $(ydata_DATA) $(ycpchook) $(ybcfiles)
+	@if test "$(filter %.ycp, $(client_DATA) $(ydata_DATA))"; then \
 	  if $(CHECK_SYNTAX); then \
-	    TO_CHECK="$(filter %.ycp,$^)"; \
+	    TO_CHECK="$(filter %.ycp, $(client_DATA) $(ydata_DATA))"; \
 	    echo "Checking syntax of $${TO_CHECK}"; \
 	    if ! $(YCPC) -qE -M. -I. $(YCPCFLAGS) $${TO_CHECK}; then \
 	      echo "Failed. Disable by 'make ... CHECK_SYNTAX=false' at your own risk"; \
@@ -43,5 +46,18 @@ check-syntax: $(client_DATA) $(ycpchook)
 	    echo "Syntax check disabled"; \
 	  fi; \
 	fi
+	@if test "$(filter %.rb, $^)"; then \
+	  if $(CHECK_SYNTAX); then \
+	    TO_CHECK="$(filter %.rb, $^)"; \
+	    echo "Checking syntax of $${TO_CHECK}"; \
+	    for f in $${TO_CHECK}; do \
+	      if ! ruby -c $$f > /dev/null; then \
+		echo "Failed. Disable by 'make ... CHECK_SYNTAX=false' at your own risk"; \
+		exit 1; \
+	      fi; \
+	    done; \
+	  else \
+	    echo "Syntax check disabled"; \
+	  fi; \
+	fi
 
--include .dep
